name: JMB's new Jekyll Site
markdown: redcarpet
pygments: true
exclude: ["vendor"]
asciidoc_ext: asciidoc,adoc,ad,txt
asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=coderay
    - coderay-css=style
